### ISSUE TITLE
Can't Edit a UserGroup

### ISSUE THREAD

**Issue by lisandi** [apeisa/UserGroups#33]
There is no way to edit a UserGroup name i.e. if you have made a typo or want to add a better description. It is only possible to remove the UserGroup and create a new one.

**Comment by teppokoivula** [comment]
Editing group descriptions and names is implemented in the [feature-edit-group-details](https://github.com/apeisa/UserGroups/tree/feature-edit-group-details) branch. Still could use some testing, though (any help appreciated).

**Comment by teppokoivula** [comment]
@lisandi This feature has just been merged to master branch. Just pull the latest version of the module, and you should see editable title and description fields in group details.

**Comment by teppokoivula** [comment]
This was fixed months ago, closing.
